### ISSUE TITLE
Allow `alt` in items fo images

### ISSUE THREAD

**Issue by rap2hpoutre** [rap2hpoutre/vue-picture-swipe#1]
Actual:

```javascript
{
  src: 'http://via.placeholder.com/600x400',
  thumbnail: 'http://via.placeholder.com/64x64',
  w: 600,
  h: 400
}
```

It would be great if we could add an **optional** `alt` property:

```javascript
{
  src: 'http://via.placeholder.com/600x400',
  thumbnail: 'http://via.placeholder.com/64x64',
  alt: 'some numbers on a grey background',
  w: 600,
  h: 400
}
```

Thanks to /u/m_roth for [the suggestion](https://www.reddit.com/r/vuejs/comments/81flr9/review_vue_picture_swipe_gallery_do_you_think_the/dv33jpr/).

**Comment by mattrothenberg** [comment]
C'est moi, u/m_roth :)

I'll make a PR this weekend!

**Comment by rap2hpoutre** [comment]
@mattrothenberg Hi, do you still want to do a PR for this?

**Comment by mattrothenberg** [comment]
Ahh, completely forgot about this. I don't think I have the time ☹️

**Comment by rap2hpoutre** [comment]
@Pochwar Do you want to tackle this issue?

**Comment by Pochwar** [comment]
Sorry, I don't have much time right now, I try to take a look this WE

**Comment by rap2hpoutre** [comment]
@Pochwar haha it's okay! :)

**Comment by tkilgour** [comment]
@rap2hpoutre Just took a look at this and I'm happy to make the fix! It looks like I can easily add the `alt` attribute to the thumbnail images, but not to the gallery images.

**Comment by rap2hpoutre** [comment]
Thank you @tkilgour 👍
