### ISSUE TITLE
Slot as Photoswipe item

### ISSUE THREAD

**Issue by nivv** [rap2hpoutre/vue-picture-swipe#10]
Wouldn't it be a good idea to have the ability to have image items as slots?

```vue
<vue-picture-swipe>
    <picture :src="https://placehold.it/600x400/xa/fff" class="col-sm-6"></picture>
    <picture :src="https://placehold.it/600x400/xa/fff" class="col-sm-6"></picture>
</vue-picture-swipe>
```

**Comment by rap2hpoutre** [comment]
> Wouldn't it be a good idea to have the ability to have image items as slots?

Yes! Still, I feel like it would be a breaking change, so I can't change the default behavior. What are your thoughts?
