### ISSUE TITLE
Logo Design Proposal

### ISSUE THREAD

**Issue by Tobaloidee** [rap2hpoutre/vue-picture-swipe#11]
Good day Sir @rap2hpoutre , I am Tobaloidee (graphics designer) and I have contributed to your other project. I just want to offer you again a logo design proposal as a gift for free. If you will permit me Sir i will do it asap. Thanks and my best regards!

**Comment by rap2hpoutre** [comment]
Hi, thank you! I remember you and your awesome work on Laravel Fast Excel 👍 !

I feel that this package does not require a logo right now: I think the relevant part of the readme is the small GIF that shows the lib running. So this lib already has its identity, thanks to this GIF with dog and mountain. And it has only 700+ downloads right now, so I think it's a tiny lib with almost no audience: it does not require a logo.

Anyway, I remember you and your work: be sure I will ask you to draw a logo if this lib become more popular! If it has, let's say, 10K downloads, maybe I will reconsider your proposal! (Still, if you consider it as an exercise for you, you are free to draw one).

Best regards!

**Comment by Tobaloidee** [comment]
Hello sir, thanks for your feedback..ofcourse i will be available if ever the project reached its height in popularity..Again Sir, best regards!
