### ISSUE TITLE
Webpack 4, mini-css-extract-plugin and Material Icons

### ISSUE THREAD

**Issue by pixelated-au** [rap2hpoutre/vue-picture-swipe#15]
Hi, it appears that the mini-css-extract-plugin as recommended when using Webpack 4 doesn't support remote requests. As such the line `318 VuePictureSwipe.vue @import "https://fonts.googleapis.com/icon?family=Material+Icons";` creates an error
```Unexpected format https://fonts.googleapis.com/icon?family=Material+Icons```

The only way to rectify it is to copy/paste the code from the remote URL in place of that line:
```
/* fallback */
@font-face {
  font-family: 'Material Icons';
  font-style: normal;
  font-weight: 400;
  src: url(https://fonts.gstatic.com/s/materialicons/v41/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.woff2) format('woff2');
}

.material-icons {
  font-family: 'Material Icons';
  font-weight: normal;
  font-style: normal;
  font-size: 24px;
  line-height: 1;
  letter-spacing: normal;
  text-transform: none;
  display: inline-block;
  white-space: nowrap;
  word-wrap: normal;
  direction: ltr;
  -moz-font-feature-settings: 'liga';
  -moz-osx-font-smoothing: grayscale;
}
```

**Comment by rap2hpoutre** [comment]
Hi, thank you for your contribution. I did not know about remote request. Feel free to submit a pull request with the fallback you copy/pasted (I could do it myself if you prefer).

**Comment by AndrewDavis** [comment]
For those who had this or a similar problem as I did, getting errors like:

> Error: <path to>/iconfont/material-icons.css
> Module build failed...
> ModuleParseError: Module parse failed: Unexpected character '

I solved it by doing what was done here: https://stackoverflow.com/a/51701648/1599699

**Comment by rap2hpoutre** [comment]
Thank you @AndrewDavis !
